sudo:     false
language: go
go:
  - "stable"
services:
  - docker

jobs:
  include:
    - stage: Test
      name: Static checks
      script: make static-checks
    - stage: Test
      name: Unit tests
      script: make test
    - stage: Build
      script: make build-all
      if: tag IS present

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: yes
  file: build/bin/*
  name: $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
  after_deploy:
    - docker run -t -v "$(pwd):/package" -w /package \
      -e OBS_USER=$OBS_USER \
      -e OBS_PASS=$OBS_PASS \
      -e OBS_PROJECT=$OBS_PROJECT \
      -e OBS_PACKAGE=$OBS_PACKAGE \
      shap/continuous_deliver \
      make obs-commit
