sudo:     false
language: go
go:
  - 1.11.x

jobs:
  include:
    - stage: Test
      name: Static checks
      script: make static-checks
    - stage: Test
      name: Unit tests
      script: make test
    - stage: Release
      branches:
        only:
          - ^(\d*\.)+\d*$
      script: make release
